# Generated by Django 5.0.6 on 2025-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_latitude_appointment_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pickup_week',
            field=models.CharField(choices=[('week1', 'Week 1'), ('week2', 'Week 2'), ('week3', 'Week 3'), ('week4', 'Week 4')], default='week1', help_text='Week of the month for pickup', max_length=10),
        ),
    ]
