# Generated by Django 5.0.6 on 2025-11-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment_pickup_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pickup_week',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pickup_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', help_text='Preferred day of the week for pickup', max_length=10),
        ),
    ]
