# Generated by Django 5.0.6 on 2025-11-21 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_appointment_pickup_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='waste_type',
            field=models.CharField(choices=[('general', 'General Waste'), ('recyclable', 'Recyclable'), ('organic', 'Organic/Compost'), ('hazardous', 'Hazardous Waste'), ('bulk', 'Bulk Items')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('residents', 'Residents'), ('staff', 'Staff'), ('admin', 'Admin')], default='residents', max_length=20),
        ),
        migrations.CreateModel(
            name='AppointmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('changes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='core.appointment')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
