# Generated by Django 5.0.6 on 2025-11-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.appointment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('confirmation', 'Pickup Confirmation'), ('approval', 'Appointment Approval'), ('cancellation', 'Cancellation'), ('reminder', 'Reminder'), ('announcement', 'Admin Announcement'), ('update', 'General Update')], default='update', max_length=20),
        ),
    ]
